import { useMemo, useState } from "react";
import type { GradeExamsResult, GradingMode } from "@closed-questions/shared";
import * as api from "../api";
import styles from "./Grading.module.css";

async function readFileText(file: File): Promise<string> {
  return await file.text();
}

export function Grading() {
  const [answerKeyFile, setAnswerKeyFile] = useState<File | null>(null);
  const [responsesFile, setResponsesFile] = useState<File | null>(null);
  const [mode, setMode] = useState<GradingMode>("strict");
  const [grading, setGrading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<GradeExamsResult | null>(null);

  const previewRows = useMemo(() => result?.rows.slice(0, 25) ?? [], [result]);

  async function handleGrade() {
    setError(null);
    setResult(null);

    if (!answerKeyFile) {
      setError("Select an answer key CSV file.");
      return;
    }
    if (!responsesFile) {
      setError("Select a student responses CSV file.");
      return;
    }

    setGrading(true);
    try {
      const [answerKeyCsv, responsesCsv] = await Promise.all([readFileText(answerKeyFile), readFileText(responsesFile)]);
      const graded = await api.gradeExams({ answerKeyCsv, responsesCsv, mode });
      setResult(graded);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Grading failed");
    } finally {
      setGrading(false);
    }
  }

  function downloadReport() {
    if (!result) return;
    const blob = new Blob([result.reportCsv], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "class_grade_report.csv";
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  return (
    <div className={styles.container}>
      {error ? (
        <div className={styles.error} role="alert">
          {error}
        </div>
      ) : null}

      <div className={styles.grid}>
        <label className={styles.field}>
          <span className={styles.label}>Answer key CSV</span>
          <input
            className={styles.input}
            type="file"
            accept=".csv,text/csv"
            onChange={(e) => setAnswerKeyFile(e.target.files?.[0] ?? null)}
          />
          <span className={styles.muted}>
            Use the CSV generated by the system (from the ZIP). For lenient grading, each key cell must look like
            KEY#ALTCOUNT (e.g. AC#5 or 13#6).
          </span>
        </label>

        <label className={styles.field}>
          <span className={styles.label}>Student responses CSV</span>
          <input
            className={styles.input}
            type="file"
            accept=".csv,text/csv"
            onChange={(e) => setResponsesFile(e.target.files?.[0] ?? null)}
          />
          <span className={styles.muted}>Must include examNumber and q1..qN columns (wide format).</span>
        </label>
      </div>

      <div className={styles.toolbar}>
        <div className={styles.radioRow}>
          <span className={styles.label}>Grading mode</span>
          <label className={styles.radio}>
            <input type="radio" name="grading-mode" checked={mode === "strict"} onChange={() => setMode("strict")} />
            Strict (all-or-nothing per question)
          </label>
          <label className={styles.radio}>
            <input type="radio" name="grading-mode" checked={mode === "lenient"} onChange={() => setMode("lenient")} />
            Lenient (proportional per alternative)
          </label>
        </div>

        <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
          {result ? (
            <button type="button" className={styles.primary} onClick={downloadReport}>
              Download grade report CSV
            </button>
          ) : null}
          <button type="button" className={styles.primary} disabled={grading} onClick={() => void handleGrade()}>
            {grading ? "Grading…" : "Grade exams"}
          </button>
        </div>
      </div>

      {result?.warnings?.length ? (
        <div className={styles.warnings} role="status">
          <strong>Warnings:</strong>
          <ul style={{ margin: "8px 0 0 18px" }}>
            {result.warnings.slice(0, 20).map((w, idx) => (
              <li key={idx}>{w}</li>
            ))}
          </ul>
          {result.warnings.length > 20 ? <div className={styles.muted}>…and {result.warnings.length - 20} more</div> : null}
        </div>
      ) : null}

      {result ? (
        <>
          <div className={styles.muted}>
            {result.rows.length} graded row{result.rows.length === 1 ? "" : "s"}.
          </div>

          <div className={styles.tableWrap}>
            <table className={styles.table}>
              <thead>
                <tr>
                  <th>Exam</th>
                  <th>Student</th>
                  <th>Total</th>
                  <th>Max</th>
                  <th>%</th>
                </tr>
              </thead>
              <tbody>
                {previewRows.map((r, idx) => {
                  const pct = r.maxScore > 0 ? (r.totalScore / r.maxScore) * 100 : 0;
                  return (
                    <tr key={`${r.examNumber}-${r.studentId}-${idx}`}>
                      <td>{r.examNumber}</td>
                      <td>{r.studentName ?? r.studentId}</td>
                      <td>{r.totalScore.toFixed(3)}</td>
                      <td>{r.maxScore}</td>
                      <td>{pct.toFixed(1)}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </>
      ) : (
        <div className={styles.muted}>
          Upload the two CSV files and run grading. The report is generated as a downloadable CSV for the whole class.
        </div>
      )}
    </div>
  );
}

